version: '{build}'
environment:
  EnableNuGetPackageRestore: true
build_script:
- ps: >-
    nuget restore TShock.4.OTAPI.sln

    msbuild TShock.4.OTAPI.sln /p:Configuration=Debug


    cd ./TShock.Modifications.Bootstrapper/bin/Debug/


    ./TShock.Modifications.Bootstrapper.exe


    cd ../../../


    msbuild ./TerrariaServerAPI/TerrariaServerAPI.csproj /p:Configuration=Debug


    msbuild TShock.4.OTAPI.sln /p:Configuration=Release


    cd ./TShock.Modifications.Bootstrapper/bin/Release/


    ./TShock.Modifications.Bootstrapper.exe


    cd ../../../


    msbuild ./TerrariaServerAPI/TerrariaServerAPI.csproj /p:Configuration=Release
artifacts:
- path: ./TerrariaServerAPI/bin/Debug
  name: MintakaDebug
- path: ./TerrariaServerAPI/bin/Release
  name: MintakaRelease
notifications:
- provider: Webhook
  url:
    secure: oQ7xfNjUEi+AWyhfiB5TRrk4P56YGhbY3bqOsa88XSW3hKKbPs/Q9Wqb1ur+JYua8rRbaLXV+3BDmVc15ZK//g==
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true